### ISSUE TITLE
Loop Tips Corrections

### ISSUE THREAD

**Issue by SaasyAss** [LoopKit/looptips#8]
Hi on the Loop Tips Doc. 

1. Page 1, the Introduction of Loop Tips has a spelling error. Under "What is Loop" - Instead of "no this does not current work" it should read .."no this does not currently work". 

2. At the top of the Introduction page, this spot in Github should be referenced as a place to provide feedback as it only says "If you have comments, please feel free to provide input at the Looped Facebook Group or in Loop's Zulipchat." 

3. In that same "What is Loop" section - It appears that the Omnipod insulin pump isn't a device that works with Loop.
 
4. On the Overview tab under the "Automated settings adjustments" it reads "What's the user is actually" it should instead read *what not what's. 

5. On the initial settings page, under "Try Open Looping First" it reads "This breaking-in phase will also let you get used to the Medtronic pump and sites." This is confusing as not everyone who will be using Loop is on a Medtronic. 

6. On Use Morning IOB page, under summary it reads "...glucose curve will not so such an aggressive..." . Think it should instead be "..glucose curve will not be such an aggressive.."

7. Exercise page "Delayed Onset Hypoglycemia can occur typically 6 to 12 hours (sometimes 24 hours) after exhaustive exercise, due to replenishment of muscle glycogen stores and enhances insulin sensitivity." should be "enhanced".

**Comment by marionbarker** [comment]
Thanks for your comments. Sorry it took so long to address all of them. I caught the last few today and will close this issue when I publish the next update.

**Comment by marionbarker** [comment]
closed with PR #49
